app:
  name: hcm-be
  env: production # development|staging|production
server:
  host: 0.0.0.0
  port: 8080
  readTimeout: 10s
  writeTimeout: 15s
  idleTimeout: 60s
  requestTimeout: 150s
observability:
  metricsEnabled: true
  pprofEnabled: true
database:
  driver: sqlserver # memory|postgres|sqlserver
  dsn: 'sqlserver://hcmfreshuser:iniP4ssword!!Sql@tabeldata.ip-dynamic.com:64123?database=devhcmrefreshment&encrypt=disable&trustServerCertificate=true'
  maxOpenConnections: 25
  maxIdleConnections: 25
  maxConnectionLifetime: 5m
  maxConnectionIdleTime: 5m
webhook:
  apiKey: 'your-webhook-api-key'
  hmacSecret: 'your-hmac-secret-key'
featureFlag:
  webhook:
    enableSignatureValidation: false
    enableTimestampValidation: false
    enableDuplicateEventIDValidation: false
http:
  mockapi:
    baseURL: 'https://690142aeff8d792314bcf1e7.mockapi.io/api'
    apiKey: 'your-mockapi-key'
    timeout: 10s
    retryCount: 2
  mockDIDXApi:
    baseURL: 'https://690142aeff8d792314bcf1e7.mockapi.io/api'
    apiKey: 'your-mockapi-key'
    timeout: 10s
    retryCount: 2
  apimDIDXApi:
    baseURL: 'https://apim-didx-stg.toyota.astra.co.id/p2/api/webhook/external/receive'
    apiKey: 'your-mockapi-key'
    timeout: 10s
    retryCount: 3
condition:
  outletIDs:
    - ALL
