app:
  name: hcm-be
  env: production # development|staging|production
server:
  host: 0.0.0.0
  port: 8080
  readTimeout: 10s
  writeTimeout: 15s
  idleTimeout: 60s
  requestTimeout: 150s
observability:
  metricsEnabled: true
  pprofEnabled: true
database:
  hcm:
    driver: sqlserver # memory|postgres|sqlserver
    dsn: 'sqlserver://hcmfreshuser:iniP4ssword!!Sql@tabeldata.ddns.net:64123?database=devhcmrefreshment&encrypt=disable&trustServerCertificate=true'
    maxOpenConnections: 25
    maxIdleConnections: 25
    maxConnectionLifetime: 5m
    maxConnectionIdleTime: 5m
  dmsAfterSales:
    driver: oracle # memory|postgres|sqlserver
    dsn: 'oracle://dmshcm:dmshcm123@tabeldata.ddns.net:61521/DMSDB'
    maxOpenConnections: 25
    maxIdleConnections: 25
    maxConnectionLifetime: 5m
    maxConnectionIdleTime: 5m
webhook:
  apiKey: 'YmLhbgVYIA9Fa7i1NSfgIgN2heBvyKNXkIqcsXC+9PUgj+PrL6xyAVgRoPpotNjrcYF2ImVHQqXVnbvbmkZ3mQ=='
  hmacSecret: 'your-hmac-secret-key'
jwt:
  secret: 'GF3AuBtUviqiWVXsoiNCvo+9c+XwcNnQ1EJw+SOqlgGh241dCsJOnx/dAmnRCJuce7bwjcJYIjaVBrYnLIKtSw=='
  issuer: 'hcm-be'
featureFlag:
  webhook:
    enableSignatureValidation: false
    enableTimestampValidation: false
    enableDuplicateEventIDValidation: false
http:
  mockapi:
    baseURL: 'https://690142aeff8d792314bcf1e7.mockapi.io/api'
    apiKey: 'your-mockapi-key'
    timeout: 10s
    retryCount: 2
  mockDIDXApi:
    baseURL: 'https://690142aeff8d792314bcf1e7.mockapi.io/api'
    apiKey: 'your-mockapi-key'
    timeout: 10s
    retryCount: 2
  apimDIDXApi:
    baseURL: 'https://syra.mpurwadi.site/api/v1/hcm/webhook/receive'
    apiKey: ''
    timeout: 10s
    retryCount: 3
  dmsApi:
    baseURL: 'https://dms-sales.mpurwadi.site/api'
    apiKey: ''
    timeout: 10s
    retryCount: 3
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkRNU0FQSSIsIm5iZiI6MTY1NzY4Njk0OCwiZXhwIjoxNjU3NzczMzQ4LCJpYXQiOjE2NTc2ODY5NDh9.bUYAvpDlEGnQl386hYhkHTaOp2msMX2jtQYcKma2JJQ'
  hmfApi:
    baseURL: 'http://apk.hmf.co.id:7070/mobile/marketing/credit-simulation.html'
    apiKey: ''
    timeout: 10s
    retryCount: 3
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkRNU0FQSSIsIm5iZiI6MTY1NzY4Njk0OCwiZXhwIjoxNjU3NzczMzQ4LCJpYXQiOjE2NTc2ODY5NDh9.bUYAvpDlEGnQl386hYhkHTaOp2msMX2jtQYcKma2JJQ'
asynq:
  redisAddr: 'localhost:6379' # use 'localhost:6379' for local development, 'redis:6379' for Docker
  redisDB: 0
  redisPassword: ''
  queue: 'default'
  concurrency: 10
condition:
  outletIDs:
    - ALL
scheduler:
  timezone: 'UTC'
  customer_seg_cron: '0 1 1 * *' # monthly, every 1st at 01:00 UTC (08:00 Jakarta)
  outlet_assign_cron: '0 0 * * *' # daily 00:00 UTC (07:00 Jakarta)
  sales_assign_cron: '0 0 * * *' # daily 00:00 UTC (07:00 Jakarta)
